/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import graph.GraphManager;

/**
 *
 * @author geevb
 */
public class welcomeView extends javax.swing.JFrame {

    /**
     * Creates new form welcomeView
     */
    public welcomeView() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonNaoOrientado = new javax.swing.JButton();
        jButtonOrientado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("Grafos Yay!");

        jButtonNaoOrientado.setText("Não-Orientado");
        jButtonNaoOrientado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNaoOrientadoActionPerformed(evt);
            }
        });

        jButtonOrientado.setText("Orientado");
        jButtonOrientado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrientadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonNaoOrientado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButtonOrientado)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNaoOrientado)
                    .addComponent(jButtonOrientado))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNaoOrientadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNaoOrientadoActionPerformed
        GraphManager gm = new GraphManager();
        this.dispose();
        gm.run(true);

    }//GEN-LAST:event_jButtonNaoOrientadoActionPerformed

    private void jButtonOrientadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrientadoActionPerformed
        GraphManager gm = new GraphManager();
        this.dispose();
        gm.run(false);
    }//GEN-LAST:event_jButtonOrientadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNaoOrientado;
    private javax.swing.JButton jButtonOrientado;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
